# Chapter 6 - Retrieving, Processing, and Storing Data

## Overview
In this chapter, I learned how data is ubiquitous and comes in various formats and sources, such as:
- Web, IoT sensors, emails, FTP, and databases.
- Lab experiments, election polls, marketing polls, and social surveys.

I now understand the importance of handling diverse datasets as a critical skill for a data professional. This chapter helped me:
1. Retrieve data in formats like CSV, Excel, JSON, HDF5, Parquet, and pickle.
2. Store data before or after analysis.
3. Access relational and NoSQL databases.

### Key Concepts
- **Relational Databases**: I learned about structured, schema-based storage (e.g., sqlite3, MySQL).
- **NoSQL Databases**: I explored flexible, schema-free storage for big data and web applications (e.g., MongoDB, Cassandra, Redis).

---

## Topics Covered

### 1. Reading and Writing CSV Files
- I used **NumPy** for efficient handling of numerical data in CSV format.
- I explored **pandas** for comprehensive support in reading/writing CSV files with advanced options.

### 2. Reading and Writing Excel Files
- I learned how to use pandas to handle `.xls` and `.xlsx` files for data analysis.

### 3. Reading and Writing JSON
- I now understand JSON as a lightweight data-interchange format.
- I used pandas methods to read/write JSON files.

### 4. Reading and Writing HDF5
- I explored HDF5, a hierarchical data format for large datasets.
- I used pandas to efficiently store and retrieve data in HDF5 format.

### 5. Reading and Writing HTML Tables
- I learned how to extract tabular data from HTML using pandas.

### 6. Reading and Writing Parquet
- I discovered Parquet as a columnar storage format optimized for analytics.
- I used pandas to handle Parquet files for efficient data storage.

### 7. Reading and Writing Pickle Objects
- I learned how to serialize and deserialize Python objects using Pickle.
- I used pandas to save/load DataFrames as pickle objects.

---

## Database Access

### 1. Lightweight Access with sqlite3
- I explored sqlite3 as a lightweight, file-based relational database.

### 2. Reading and Writing Data from MySQL
- I learned how to interact with MySQL, a popular relational database for structured data.

### 3. Reading and Writing Data from MongoDB
- I worked with MongoDB, a NoSQL database storing data in a document-oriented format.

### 4. Reading and Writing Data from Cassandra
- I explored Cassandra, a NoSQL database designed for high availability and scalability.

### 5. Reading and Writing Data from Redis
- I learned about Redis, an in-memory NoSQL database for fast data access.

---

## Additional Tools
- I discovered **PonyORM**, an Object-Relational Mapping (ORM) library for Python that simplifies database interactions.

---

## Summary
By the end of this chapter, I gained the skills to:
1. Retrieve data from various formats and sources.
2. Process and analyze data efficiently.
3. Store data in relational and NoSQL databases.
4. Use tools like pandas, NumPy, and database libraries for seamless data handling.

In [1]:
# import genfromtxt function
from numpy import genfromtxt
# Read comma separated file
product_data = genfromtxt('demo.csv', delimiter=',')
# display initial 5 records
print(product_data)

[[14. 32. 33.]
 [24. 45. 26.]
 [27. 38. 39.]]


In [6]:
# import pandas
import pandas as pd
# Read CSV file
df=pd.read_csv('demo.csv', sep=',' , header=None)
# Save DataFrame object in pickle file
df.to_pickle('demo_obj.pkl')

In [7]:
#Read DataFrame object from pickle file
pickle_obj=pd.read_pickle('demo_obj.pkl')
# display initial 5 records
pickle_obj.head()

0   1   2
0  14  32  33
1  24  45  26
2  27  38  39

## Lightweight Access with SQLite3

### Overview
SQLite is an open-source, lightweight database engine that is widely used in mobile and desktop applications. It is known for its simplicity, efficiency, and ability to be embedded into applications.

### Key Features
- **Faster Execution**: Optimized for speed and performance.
- **Lightweight Processing**: Minimal resource usage.
- **Serverless Architecture**: No need for a separate server; runs as part of the application.
- **ACID Compliance**: Ensures reliable transactions with Atomicity, Consistency, Isolation, and Durability.
- **High Stability**: Reliable and robust for small-scale data storage.
- **Embedded Relational Database**: Runs within the application, making it ideal for local data storage.

### Use Cases
- Best suited for small-scale data storage and processing.
- Commonly used in mobile and desktop applications for local data management.

### Advantages
- Easy to use and integrate into applications.
- Efficient and lightweight.
- No need for additional installation as it is included in standard Python distributions.
- Can store the database in a file or in RAM.

### SQLite in Python
- The `sqlite3` module in Python provides tools to read and write data to SQLite databases.
- No third-party application server is required.
- SQL queries can be executed directly using the `sqlite3` module.

### Summary
SQLite is a reliable, lightweight database solution for applications requiring local data storage. Its ease of use and integration with Python make it a popular choice for developers.

In [12]:
# Execute SQL query and create the database table
cur.execute("create table if not exists emp(eid int,salary int)")
# Execute SQL query and Write the data into database
cur.execute("insert into emp values(105, 57000)")
# Commit the transaction
conn.commit()
# Execute SQL query and Read the data from the database
cur.execute('select * from emp')
# Fetch records
print(cur.fetchall())

[(105, 57000)]


### Using the sqlite3 Module in Python

### Overview
The `sqlite3` module in Python is used to interact with SQLite databases. It provides tools to create, read, write, and manage databases efficiently.

### Key Steps

1. **Importing the Module**:
    - Use `import sqlite3` to include the module in your script.

2. **Establishing a Connection**:
    - Use the `connect()` method to create a connection to the database.
    - Syntax: `conn = sqlite3.connect('database_name.db')`
    - If the database does not exist, it will be created with the specified name and location.

3. **Creating a Cursor Object**:
    - Use the `cursor()` method on the connection object to create a cursor.
    - Syntax: `cur = conn.cursor()`
    - The cursor is used to execute SQL queries.

4. **Executing SQL Queries**:
    - Use the `execute()` method on the cursor object to run SQL queries.
    - Example:
      - Creating a table: `cur.execute("CREATE TABLE emp (eid INT, salary INT)")`
      - Inserting data: `cur.execute("INSERT INTO emp VALUES (105, 57000)")`

5. **Committing Changes**:
    - Use the `commit()` method on the connection object to save changes to the database.
    - Syntax: `conn.commit()`

6. **Fetching Data**:
    - Use the `execute()` method with a `SELECT` query to retrieve data.
    - Fetch methods:
      - `fetchone()`: Retrieves a single record.
      - `fetchall()`: Retrieves all records.
    - Example:
      ```python
      cur.execute("SELECT * FROM emp")
      records = cur.fetchall()
      ```

### Summary
The `sqlite3` module simplifies database operations in Python. It allows you to create and manage databases, execute SQL queries, and fetch data efficiently. Key methods include `connect()`, `execute()`, `commit()`, `fetchone()`, and `fetchall()`.