In [13]:
# Creating an array
import numpy as np
a = np.array ([2,4,6,8,10])
print (a)

[ 2  4  6  8 10]


In [14]:
# Creating an array using arange()
import numpy as np
a = np.arange (1,11)
print (a)

[ 1  2  3  4  5  6  7  8  9 10]


In [15]:
# Create an array of all zeros
import numpy as np
p = np.zeros ((3,3))
print (p)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
# Create an array filled with random values

t = np.random.random ((3,3))
print (t)

[[0.69040708 0.29555873 0.32366966]
 [0.30296494 0.13426176 0.7876061 ]
 [0.37427017 0.35867239 0.86002981]]


**dtype Objects**

In [17]:
# Creating an array
import numpy as np
a = np.array ([2,4,6,8,10])
print (a.dtype)

print (a.dtype.itemsize)

int64
8


In [18]:
# Create numpy array using arange() function
var1=np.arange(1,11, dtype='f')
print (var1)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


**Manipulating array shapes**

In [19]:
#Create an array
arr = np.arange(12)
print (arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [20]:
#Reshape the array dimension
new_arr=arr.reshape(3,4)

print(new_arr)

print (arr.ravel())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


**Partitioning NumPy Arrays**

**Horizontal splitting:** In horizontal split, the given array is divided into N equal sub-arrays along the horizontal axis using the hsplit() function. Let's see how to split an array:

In [21]:
import numpy as np
# Create an array
arr=np.arange (1,10). reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
# Peroform horizontal splitting
arr_hor_split=np.hsplit(arr, 3)
print(arr_hor_split)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


**Vertical splitting:** In vertical split, the given array is divided into N equal subarrays along the vertical axis using the vsplit() and split() functions. The split function with axis=0 performs the same operation as the vsplit() function:

In [23]:
# vertical split
arr_ver_split=np.vsplit(arr, 3)
print(arr_ver_split)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [24]:
# split with axis=0
arr_split=np.split(arr,3,axis=0)
print(arr_split)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [25]:
# split with axis=1
arr_split = np.split(arr,3,axis=1)
print(arr_split)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


**Boolean and fancy indexing**
Indexing techniques help us to select and filter elements from a NumPy array. In this section, we will focus on Boolean and fancy indexing. Boolean indexing uses a Boolean
expression in the place of indexes (in square brackets) to filter the NumPy array. This indexing returns elements that have a true value for the Boolean expression:

In [26]:
# Create NumPy Array
arr = np.arange(21,41,2)
print("Orignial Array:\n",arr)

Orignial Array:
 [21 23 25 27 29 31 33 35 37 39]


In [27]:
# Boolean Indexing
print("After Boolean Condition:",arr[arr>30])

After Boolean Condition: [31 33 35 37 39]


**Fancy indexing** is a special type of indexing in which elements of an array are selected by an array of indices. This means we pass the array of indices in brackets. Fancy indexing also supports multi-dimensional arrays. This will help us to easily select and modify a complex multi-dimensional set of arrays.

In [28]:
# Create NumPy Array
arr = np.arange(1,21).reshape(5,4)
print("Orignial Array:\n",arr)

Orignial Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [29]:
# Selecting 2nd and 3rd row
indices = [1,2]
print("Selected 1st and 2nd Row:\n", arr[indices])

Selected 1st and 2nd Row:
 [[ 5  6  7  8]
 [ 9 10 11 12]]


In [30]:
# Selecting 3nd and 4th row
indices = [2,3]
print("Selected 3rd and 4th Row:\n", arr[indices])

Selected 3rd and 4th Row:
 [[ 9 10 11 12]
 [13 14 15 16]]


## Creating pandas DataFrames

In [31]:
# Import pandas library
import pandas as pd

# Create empty DataFrame
df = pd.DataFrame()

# Header of dataframe.
df.head()

Empty DataFrame
Columns: []
Index: []

In [32]:
# Create dictionary of list
data = {'Name': ['Vijay', 'Sundar', 'Satyam', 'Indira'], 'Age': [23, 45,
46, 52 ]}

# Create the pandas DataFrame
df = pd.DataFrame(data)

# Header of dataframe.
df.head ()

Name  Age
0   Vijay   23
1  Sundar   45
2  Satyam   46
3  Indira   52

In [33]:
# Pandas DataFrame by lists of dicts.
# Initialise data to lists.

data =[ {'Name': 'Vijay', 'Age': 23},{'Name': 'Sundar', 'Age': 25},{'Name':
'Shankar', 'Age': 26}]

# Creates DataFrame.
df = pd.DataFrame(data,columns=['Name','Age'])

# Print dataframe header
df.head()

Name  Age
0    Vijay   23
1   Sundar   25
2  Shankar   26

In [34]:
# Creating DataFrame using list of tuples.
data = [('Vijay', 23),( 'Sundar', 45), ('Satyam', 46), ('Indira',52)]

# Create dataframe
df = pd.DataFrame(data, columns=['Name','Age'])

# Print dataframe header
df.head()

Name  Age
0   Vijay   23
1  Sundar   45
2  Satyam   46
3  Indira   52

In [35]:
# Creating Pandas Series using Dictionary
dict1 = {0 : 'Ajay', 1 : 'Jay', 2 : 'Vijay'}

# Create Pandas Series
series = pd.Series(dict1)

#show series
series



0     Ajay
1      Jay
2    Vijay
dtype: object

In [36]:
#Load Pandas and NumPy libraries
import pandas as pd
import numpy as np

# Create NumPy array
arr = np.array([51,65,48,59, 68])

# Create Pandas Series
series = pd.Series(arr)

series

0    51
1    65
2    48
3    59
4    68
dtype: int64

In [37]:
# load Pandas and NumPy
import pandas as pd
import numpy as np

# Create Pandas Series
series = pd.Series(10, index=[0, 1, 2, 3, 4, 5])
series


0    10
1    10
2    10
3    10
4    10
5    10
dtype: int64

In [38]:
#Import pandas
import pandas as pd

# Load data using read_csv()
df = pd.read_csv("WHO_first9cols.csv")

# Show initial 5 records
df.head()


Country  CountryID  Continent  Adolescent fertility rate (%)  \
0  Afghanistan          1          1                          151.0   
1      Albania          2          2                           27.0   
2      Algeria          3          3                            6.0   
3      Andorra          4          2                            NaN   
4       Angola          5          3                          146.0   

   Adult literacy rate (%)  \
0                     28.0   
1                     98.7   
2                     69.9   
3                      NaN   
4                     67.4   

   Gross national income per capita (PPP international $)  \
0                                                NaN        
1                                             6000.0        
2                                             5940.0        
3                                                NaN        
4                                             3890.0        

   Net primary school enrolment ratio female (%)  \
0                                            NaN   
1                                           93.0   
2                                           94.0   
3                                           83.0   
4                                           49.0   

   Net primary school enrolment ratio male (%)  \
0                                          NaN   
1                                         94.0   
2                                         96.0   
3                                         83.0   
4                                         51.0   

   Population (in thousands) total  
0                          26088.0  
1                           3172.0  
2                          33351.0  
3                             74.0  
4                          16557.0

In [39]:
# Select a series
country_series=df['Country']
# check datatype of series
type(country_series)

pandas.core.series.Series

In [40]:
# Show the shape of DataFrame
print("Shape:", df.shape)

Shape: (202, 9)


In [41]:
# Check the column list of DataFrame
print("List of Columns:", df.columns)

List of Columns: Index(['Country', 'CountryID', 'Continent', 'Adolescent fertility rate (%)',
       'Adult literacy rate (%)',
       'Gross national income per capita (PPP international $)',
       'Net primary school enrolment ratio female (%)',
       'Net primary school enrolment ratio male (%)',
       'Population (in thousands) total'],
      dtype='object')


In [42]:
# Show the datatypes of columns
print("Data types:", df.dtypes)

Data types: Country                                                    object
CountryID                                                   int64
Continent                                                   int64
Adolescent fertility rate (%)                             float64
Adult literacy rate (%)                                   float64
Gross national income per capita (PPP international $)    float64
Net primary school enrolment ratio female (%)             float64
Net primary school enrolment ratio male (%)               float64
Population (in thousands) total                           float64
dtype: object


In [43]:
# Pandas Series Slicing
country_series[-5:]

197               Vietnam
198    West Bank and Gaza
199                 Yemen
200                Zambia
201              Zimbabwe
Name: Country, dtype: object

## Taxi Company Use Case

In [44]:
#Import pandas
import pandas as pd

# Load data using read_csv()

dest = pd.read_csv("dest.csv")

# Show DataFrame
dest.head()



EmpNr       Dest
0      5  The Hague
1      3  Amsterdam
2      9  Rotterdam

In [45]:
#Load data using read_csv()
tips = pd.read_csv("tips.csv")
# Show DataFrame

tips.head()

EmpNr  Amount
0      5    10.0
1      9     5.0
2      7     2.5

In [46]:
# Join DataFrames using Inner Join
df_inner= pd.merge(dest, tips, on='EmpNr', how='inner')
df_inner.head()

EmpNr       Dest  Amount
0      5  The Hague    10.0
1      9  Rotterdam     5.0

## Creating pivot tables

In [47]:
# Import pandas
import pandas as pd
# Load data using read_csv()

purchase = pd.read_csv("purchase.csv")
# Show initial 10 records

purchase.head(10)

Weather       Food     Price  Number
0    cold       soup  3.745401       8
1     hot       soup  9.507143       8
2    cold   icecream  7.319939       8
3     hot  chocolate  5.986585       8
4    cold   icecream  1.560186       8
5     hot   icecream  1.559945       8
6    cold       soup  0.580836       8

In [48]:
# Summarise dataframe using pivot table

pd.pivot_table(purchase,values='Number', index=['Weather',],
               columns=['Food'], aggfunc=np.sum)

/var/folders/mz/gry90mxx4gvbsvhp15tw7bhh0000gn/T/ipykernel_97111/1816314235.py:3: FutureWarning: The provided callable <function sum at 0x118ad1d00> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.pivot_table(purchase,values='Number', index=['Weather',],


Food     chocolate  icecream  soup
Weather                           
cold           NaN      16.0  16.0
hot            8.0       8.0   8.0